// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: access.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAccess = `-- name: AddAccess :exec
INSERT INTO access (
	user_id,
  ip_address
) VALUES ($1, $2)
`

type AddAccessParams struct {
	UserID    pgtype.Int4
	IpAddress string
}

func (q *Queries) AddAccess(ctx context.Context, arg AddAccessParams) error {
	_, err := q.db.Exec(ctx, addAccess, arg.UserID, arg.IpAddress)
	return err
}
