// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package repository

import (
	"context"
)

const getPrinterConfig = `-- name: GetPrinterConfig :one
SELECT value from config where key = 'thermal-printer' LIMIT 1
`

func (q *Queries) GetPrinterConfig(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPrinterConfig)
	var value []byte
	err := row.Scan(&value)
	return value, err
}
