// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: letter.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLetter = `-- name: CreateLetter :one
INSERT INTO letter (title, content, recipient, sender, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateLetterParams struct {
	Title     string
	Content   string
	Recipient string
	Sender    string
	CreatedBy int32
}

func (q *Queries) CreateLetter(ctx context.Context, arg CreateLetterParams) (int32, error) {
	row := q.db.QueryRow(ctx, createLetter,
		arg.Title,
		arg.Content,
		arg.Recipient,
		arg.Sender,
		arg.CreatedBy,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteLastLetter = `-- name: DeleteLastLetter :exec
DELETE FROM letter
WHERE id = (
	SELECT id FROM letter as l
	WHERE l.created_by = $1
	ORDER BY created_at DESC
	LIMIT 1
)
`

func (q *Queries) DeleteLastLetter(ctx context.Context, createdBy int32) error {
	_, err := q.db.Exec(ctx, deleteLastLetter, createdBy)
	return err
}

const getLetterByID = `-- name: GetLetterByID :one
SELECT id, title, content, recipient, sender, created_at, created_by, updated_at FROM letter WHERE id = $1
`

func (q *Queries) GetLetterByID(ctx context.Context, id int32) (Letter, error) {
	row := q.db.QueryRow(ctx, getLetterByID, id)
	var i Letter
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Recipient,
		&i.Sender,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const totalLettersFromUser = `-- name: TotalLettersFromUser :one
SELECT count(*) AS total FROM letter
WHERE created_by = $1
AND created_at >= $2
AND created_at < $3
`

type TotalLettersFromUserParams struct {
	CreatedBy   int32
	CreatedAt   pgtype.Timestamp
	CreatedAt_2 pgtype.Timestamp
}

func (q *Queries) TotalLettersFromUser(ctx context.Context, arg TotalLettersFromUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, totalLettersFromUser, arg.CreatedBy, arg.CreatedAt, arg.CreatedAt_2)
	var total int64
	err := row.Scan(&total)
	return total, err
}
