// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: list.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createList = `-- name: CreateList :one
INSERT INTO list (title, content, created_by)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateListParams struct {
	Title     string
	Content   pgtype.Text
	CreatedBy int32
}

func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (int32, error) {
	row := q.db.QueryRow(ctx, createList, arg.Title, arg.Content, arg.CreatedBy)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteLastList = `-- name: DeleteLastList :exec
DELETE FROM list
WHERE id = (
	SELECT id FROM task as t
	WHERE t.created_by = $1
	ORDER BY created_at DESC
	LIMIT 1
)
`

func (q *Queries) DeleteLastList(ctx context.Context, createdBy int32) error {
	_, err := q.db.Exec(ctx, deleteLastList, createdBy)
	return err
}

const totalListsFromUser = `-- name: TotalListsFromUser :one
SELECT count(*) AS total FROM list
WHERE created_by = $1
AND created_at >= $2
AND created_at < $3
`

type TotalListsFromUserParams struct {
	CreatedBy   int32
	CreatedAt   pgtype.Timestamp
	CreatedAt_2 pgtype.Timestamp
}

func (q *Queries) TotalListsFromUser(ctx context.Context, arg TotalListsFromUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, totalListsFromUser, arg.CreatedBy, arg.CreatedAt, arg.CreatedAt_2)
	var total int64
	err := row.Scan(&total)
	return total, err
}
