// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: list.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createList = `-- name: CreateList :one
INSERT INTO list (title, content, created_by)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateListParams struct {
	Title     string
	Content   pgtype.Text
	CreatedBy int32
}

func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (int32, error) {
	row := q.db.QueryRow(ctx, createList, arg.Title, arg.Content, arg.CreatedBy)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const totalListsFromUserToday = `-- name: TotalListsFromUserToday :one
SELECT COUNT(*) AS total FROM list 
WHERE created_by = $1 
AND DATE(created_at) = CURRENT_DATE
`

func (q *Queries) TotalListsFromUserToday(ctx context.Context, createdBy int32) (int64, error) {
	row := q.db.QueryRow(ctx, totalListsFromUserToday, createdBy)
	var total int64
	err := row.Scan(&total)
	return total, err
}
