// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Access struct {
	ID         int32
	UserID     pgtype.Int4
	IpAddress  string
	AccessedAt pgtype.Timestamp
	Path       string
	Method     string
}

type Config struct {
	ID        int32
	Key       string
	Value     []byte
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Link struct {
	ID        int32
	Url       string
	Title     string
	CreatedAt pgtype.Timestamp
	CreatedBy int32
	UpdatedAt pgtype.Timestamp
}

type List struct {
	ID        int32
	Title     string
	Content   pgtype.Text
	CreatedAt pgtype.Timestamp
	CreatedBy int32
	UpdatedAt pgtype.Timestamp
}

type Schedule struct {
	ID             int32
	Name           string
	Title          string
	Description    pgtype.Text
	CronExpression string
	Enabled        bool
	CreatedBy      int32
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	CheckFunction  pgtype.Text
}

type Task struct {
	ID          int32
	Title       string
	Description pgtype.Text
	Priority    pgtype.Int4
	CreatedAt   pgtype.Timestamp
	CreatedBy   int32
	UpdatedAt   pgtype.Timestamp
	CompletedAt pgtype.Timestamp
}

type User struct {
	ID        int32
	Name      string
	ApiKey    string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
