// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package repository

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO public."user" (
		name,
		api_key
) VALUES ($1, $2)
RETURNING id
`

type CreateUserParams struct {
	Name   string
	ApiKey string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.ApiKey)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getUserById = `-- name: GetUserById :one
select id, name from public."user" where id = $1
`

type GetUserByIdRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetUserById(ctx context.Context, id int32) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getUserByKey = `-- name: GetUserByKey :one
select id, name from public."user" where api_key = $1
`

type GetUserByKeyRow struct {
	ID   int32
	Name string
}

func (q *Queries) GetUserByKey(ctx context.Context, apiKey string) (GetUserByKeyRow, error) {
	row := q.db.QueryRow(ctx, getUserByKey, apiKey)
	var i GetUserByKeyRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
