@host = https://ticket.joaoporta.com

# @host http://localhost:8000

POST {{host}}/link HTTP/1.1
X-Api-Key: {{API_KEY}}

{
  "title": "Compras",
  "url": "https://www.amazon.com.br/hz/wishlist/ls/1A2B3C4D5E6F7G?ref_=wl_share"
}
