#@host = https://ticket.joaoporta.com
@host = localhost:8000

POST {{host}}/task HTTP/1.1
X-Api-Key: {{API_KEY}}

{
  "description": "Create simple bash to send tasks",
  "priority": 2,
  "title": "Task Management"
}
