# @host = localhost:8000
@host = https://ticket.joaoporta.com

POST {{host}}/schedule HTTP/1.1
X-Api-Key: {{API_KEY}}

{
	"name": "Reminder Cidinha",
	"title": "Grupo Cidinha",
	"description":"Avisar Cidinha que tem grupo de domesticas, e pedir para conversar com alguma outra pessoa na saida",
	"cron_expression": "0 8 4 9 *"
}
###
GET {{host}}/schedule HTTP/2
X-Api-Key: {{API_KEY}}

###
GET {{host}}/schedule HTTP/1.1
X-Api-Key: {{API_KEY}}

###
PUT {{host}}/schedule?id=11 HTTP/1.1
X-Api-Key: {{API_KEY}}
