# @host = localhost:8000
@host = https://ticket.joaoporta.com

POST {{host}}/schedule HTTP/1.1
X-Api-Key: {{API_KEY}}

{
	"name": "Ouvido Cachorras",
	"title": "Ouvido Cachorras",
	"description":"Limpar e passar remedio no ouvido das cachorras",
	"cron_expression": "0 17 * * 2,6"
}
###
GET {{host}}/schedule HTTP/2
X-Api-Key: {{API_KEY}}

###
GET {{host}}/schedule HTTP/1.1
X-Api-Key: {{API_KEY}}

###
PUT {{host}}/schedule?id=11 HTTP/1.1
X-Api-Key: {{API_KEY}}
