@host = localhost:8000
# @host = https://ticket.joaoporta.com

POST {{host}}/schedule HTTP/1.1
X-Api-Key: {{API_KEY}}

{
	"name": "mandarim",
	"title": "HelloChinese",
	"description":"Estudar pelo menos 15 minutos",
	"cron_expression": "35 18 * * 1-5"
}
###
GET {{host}}/schedule HTTP/2
X-Api-Key: {{API_KEY}}

###
GET {{host}}/schedule HTTP/1.1
X-Api-Key: {{API_KEY}}

###
PUT {{host}}/schedule?id=11 HTTP/1.1
X-Api-Key: {{API_KEY}}
