// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.31.1
// source: protobuf/printer.proto

package printer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrintJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Img []byte `protobuf:"bytes,1,opt,name=img,proto3" json:"img,omitempty"`
}

func (x *PrintJob) Reset() {
	*x = PrintJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_printer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrintJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintJob) ProtoMessage() {}

func (x *PrintJob) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_printer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintJob.ProtoReflect.Descriptor instead.
func (*PrintJob) Descriptor() ([]byte, []int) {
	return file_protobuf_printer_proto_rawDescGZIP(), []int{0}
}

func (x *PrintJob) GetImg() []byte {
	if x != nil {
		return x.Img
	}
	return nil
}

type PrintLinkJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url    string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Header []byte `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *PrintLinkJob) Reset() {
	*x = PrintLinkJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_printer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrintLinkJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintLinkJob) ProtoMessage() {}

func (x *PrintLinkJob) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_printer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintLinkJob.ProtoReflect.Descriptor instead.
func (*PrintLinkJob) Descriptor() ([]byte, []int) {
	return file_protobuf_printer_proto_rawDescGZIP(), []int{1}
}

func (x *PrintLinkJob) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PrintLinkJob) GetHeader() []byte {
	if x != nil {
		return x.Header
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_printer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_printer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protobuf_printer_proto_rawDescGZIP(), []int{2}
}

var File_protobuf_printer_proto protoreflect.FileDescriptor

var file_protobuf_printer_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x72, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x22, 0x1c, 0x0a, 0x08, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x4a, 0x6f, 0x62, 0x12, 0x10, 0x0a,
	0x03, 0x69, 0x6d, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x69, 0x6d, 0x67, 0x22,
	0x38, 0x0a, 0x0c, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x4a, 0x6f, 0x62, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x32, 0x69, 0x0a, 0x07, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x2a, 0x0a,
	0x05, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x12, 0x11, 0x2e, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x2e, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x4a, 0x6f, 0x62, 0x1a, 0x0e, 0x2e, 0x70, 0x72, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x32, 0x0a, 0x09, 0x50, 0x72, 0x69,
	0x6e, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x2e, 0x50, 0x72, 0x69, 0x6e, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x4a, 0x6f, 0x62, 0x1a, 0x0e, 0x2e,
	0x70, 0x72, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x0b, 0x5a,
	0x09, 0x2e, 0x2f, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protobuf_printer_proto_rawDescOnce sync.Once
	file_protobuf_printer_proto_rawDescData = file_protobuf_printer_proto_rawDesc
)

func file_protobuf_printer_proto_rawDescGZIP() []byte {
	file_protobuf_printer_proto_rawDescOnce.Do(func() {
		file_protobuf_printer_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_printer_proto_rawDescData)
	})
	return file_protobuf_printer_proto_rawDescData
}

var file_protobuf_printer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_printer_proto_goTypes = []interface{}{
	(*PrintJob)(nil),     // 0: printer.PrintJob
	(*PrintLinkJob)(nil), // 1: printer.PrintLinkJob
	(*Empty)(nil),        // 2: printer.Empty
}
var file_protobuf_printer_proto_depIdxs = []int32{
	0, // 0: printer.Printer.Print:input_type -> printer.PrintJob
	1, // 1: printer.Printer.PrintLink:input_type -> printer.PrintLinkJob
	2, // 2: printer.Printer.Print:output_type -> printer.Empty
	2, // 3: printer.Printer.PrintLink:output_type -> printer.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_printer_proto_init() }
func file_protobuf_printer_proto_init() {
	if File_protobuf_printer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_printer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrintJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_printer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrintLinkJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_printer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_printer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_printer_proto_goTypes,
		DependencyIndexes: file_protobuf_printer_proto_depIdxs,
		MessageInfos:      file_protobuf_printer_proto_msgTypes,
	}.Build()
	File_protobuf_printer_proto = out.File
	file_protobuf_printer_proto_rawDesc = nil
	file_protobuf_printer_proto_goTypes = nil
	file_protobuf_printer_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PrinterClient is the client API for Printer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrinterClient interface {
	Print(ctx context.Context, in *PrintJob, opts ...grpc.CallOption) (*Empty, error)
	PrintLink(ctx context.Context, in *PrintLinkJob, opts ...grpc.CallOption) (*Empty, error)
}

type printerClient struct {
	cc grpc.ClientConnInterface
}

func NewPrinterClient(cc grpc.ClientConnInterface) PrinterClient {
	return &printerClient{cc}
}

func (c *printerClient) Print(ctx context.Context, in *PrintJob, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/printer.Printer/Print", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *printerClient) PrintLink(ctx context.Context, in *PrintLinkJob, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/printer.Printer/PrintLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrinterServer is the server API for Printer service.
type PrinterServer interface {
	Print(context.Context, *PrintJob) (*Empty, error)
	PrintLink(context.Context, *PrintLinkJob) (*Empty, error)
}

// UnimplementedPrinterServer can be embedded to have forward compatible implementations.
type UnimplementedPrinterServer struct {
}

func (*UnimplementedPrinterServer) Print(context.Context, *PrintJob) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Print not implemented")
}
func (*UnimplementedPrinterServer) PrintLink(context.Context, *PrintLinkJob) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintLink not implemented")
}

func RegisterPrinterServer(s *grpc.Server, srv PrinterServer) {
	s.RegisterService(&_Printer_serviceDesc, srv)
}

func _Printer_Print_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrinterServer).Print(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/printer.Printer/Print",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrinterServer).Print(ctx, req.(*PrintJob))
	}
	return interceptor(ctx, in, info, handler)
}

func _Printer_PrintLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintLinkJob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrinterServer).PrintLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/printer.Printer/PrintLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrinterServer).PrintLink(ctx, req.(*PrintLinkJob))
	}
	return interceptor(ctx, in, info, handler)
}

var _Printer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "printer.Printer",
	HandlerType: (*PrinterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Print",
			Handler:    _Printer_Print_Handler,
		},
		{
			MethodName: "PrintLink",
			Handler:    _Printer_PrintLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/printer.proto",
}
